# Generated by Django 4.1.3 on 2023-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('category', models.CharField(choices=[('Business Law', 'Business Law'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
