# Generated by Django 4.1.3 on 2023-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='icon',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Business Law', 'Business Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
    ]
