# Generated by Django 4.1.3 on 2023-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slider_icon_alter_slider_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/asosiy/')),
            ],
        ),
        migrations.CreateModel(
            name='BigSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
    ]
