# Generated by Django 4.1.3 on 2023-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bigslide_category_alter_slider_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/team/')),
                ('name', models.CharField(max_length=100)),
                ('staff', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Family Law', 'Family Law'), ('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Family Law', 'Family Law'), ('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
    ]
