# Generated by Django 4.1.3 on 2023-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_team_alter_bigslide_category_alter_slider_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='insta',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='linkedn',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='telegram',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Business Law', 'Business Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Business Law', 'Business Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
    ]
