# Generated by Django 4.1.3 on 2023-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_team_facebook_team_insta_team_linkedn_team_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('orign', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
    ]
