# Generated by Django 4.1.3 on 2023-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comments_alter_bigslide_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='category',
            field=models.CharField(choices=[('Baddies', 'Baddies'), ('Goodies', 'Goodies')], default='Goodies', max_length=100),
        ),
    ]
