# Generated by Django 4.1.3 on 2023-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comments_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='orign',
        ),
        migrations.AlterField(
            model_name='comments',
            name='category',
            field=models.CharField(choices=[('Goodies', 'Goodies'), ('Baddies', 'Baddies')], default='Goodies', max_length=100),
        ),
    ]
