# Generated by Django 4.1.3 on 2023-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_comments_orign_alter_comments_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='category',
            field=models.CharField(choices=[('Baddies', 'Baddies'), ('Goodies', 'Goodies')], default='Goodies', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
    ]
