# Generated by Django 4.1.7 on 2023-03-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_bigslide_category_alter_slider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
    ]
