# Generated by Django 4.1.7 on 2023-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_bigslide_category_alter_slider_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law')], default='Business Law', max_length=100),
        ),
    ]
