# Generated by Django 4.1.7 on 2023-03-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_izoh_alter_bigslide_category_alter_slider_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/contct/')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='category',
            field=models.CharField(choices=[('Goodies', 'Goodies'), ('Baddies', 'Baddies')], default='Goodies', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
    ]
