# Generated by Django 4.1.7 on 2023-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contacpage_alter_bigslide_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('phone', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='category',
            field=models.CharField(choices=[('Baddies', 'Baddies'), ('Goodies', 'Goodies')], default='Goodies', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
    ]
