# Generated by Django 4.1.7 on 2023-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_message_alter_bigslide_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('number', models.IntegerField()),
                ('photo1', models.ImageField(upload_to='media/about/')),
                ('photo2', models.ImageField(upload_to='media/about/')),
            ],
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
    ]
