# Generated by Django 4.1.7 on 2023-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_aboutslide_alter_bigslide_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXPERIENCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('number', models.IntegerField()),
                ('title2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law'), ('Business Law', 'Business Law')], default='Business Law', max_length=100),
        ),
    ]
