# Generated by Django 4.1.7 on 2023-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_news_alter_bigslide_category_alter_comments_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigslide',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Business Law', 'Business Law'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law')], default='Business Law', max_length=100),
        ),
    ]
