# Generated by Django 4.1.7 on 2023-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_bigslide_category_alter_slider_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='category',
            field=models.CharField(choices=[('Baddies', 'Baddies'), ('Goodies', 'Goodies')], default='Goodies', max_length=100),
        ),
    ]
